import { collections, connect } from "@/lib/dbConnect";
import React from "react";
import CampaignCard from "./CampaignCard";
export const metadata = {
  title: "Campaigns",
  description: "Generated by Humanity",
};

const Campaigns = async () => {
  const campaigns = await connect(collections.CAMPAIGNS).find().toArray();
  return (
    <div>
      <div className="text-center my-6">
        <h2 className="text-secondary text-2xl md:text-4xl font-bold">
          Campaigns
        </h2>
        <p className="text-accent-content md:font-bold my-3">
          Quickly see how you can help and track progress in real-time
        </p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {campaigns.map((campaign) => (
          <CampaignCard key={campaign._id} campaign={campaign}></CampaignCard>
        ))}
      </div>
      <div></div>
    </div>
  );
};

export default Campaigns;
