import { singleCampaign } from "@/components/actions/server/campaign";
import Image from "next/image";
export const metadata = {
  title: "Campaign Details",
  description: "Generated by Humanity",
};

const CampaignDetails = async ({ params }) => {
  const { id } = await params;

  const campaign = await singleCampaign(id);

  return (
    <div className="max-w-6xl mx-auto px-4 py-10">
      {/* Image */}
      <div className="relative w-full h-88 md:h-112 rounded-xl overflow-hidden shadow-lg ">
        <Image
          src={campaign?.image}
          alt={campaign?.title}
          width={1200}
          height={800}
          className="object-cover"
        />
      </div>

      {/* Content */}
      <div className="mt-8 grid md:grid-cols-3 gap-8">
        {/* Left Section */}
        <div className="md:col-span-2 space-y-4">
          <h1 className="text-3xl md:text-4xl font-bold text-primary">
            {campaign?.title}
          </h1>

          <p className="text-gray-600 leading-relaxed text-lg">
            {campaign?.description}
          </p>

          {/* Info */}
          <div className="flex flex-wrap gap-4 mt-4">
            <span className="badge badge-outline badge-primary">
              {campaign?.category}
            </span>

            <span className="badge badge-outline">📍 {campaign?.location}</span>

            <span className="badge badge-outline badge-warning">
              Deadline: {campaign?.deadline}
            </span>
          </div>
        </div>

        {/* Right Section / Donation Card */}
        <div className="card bg-base-100 shadow-xl p-6 space-y-4">
          <h3 className="text-xl font-bold">Support this Campaign</h3>

          <p className="text-sm text-gray-500">
            Your donation helps renovate the mosque so the community can pray
            comfortably.
          </p>

          {/* Example Progress */}
          <progress
            className="progress progress-primary w-full"
            value="40"
            max="100"
          ></progress>

          <div className="flex justify-between text-sm">
            <span>$4,000 raised</span>
            <span>Goal: $10,000</span>
          </div>

          <button className="btn btn-primary w-full">Donate Now</button>
        </div>
      </div>

      {/* Extra Section */}
      <div className="mt-12">
        <h2 className="text-2xl font-bold mb-3">Why This Campaign Matters</h2>
        <p className="text-gray-600 leading-relaxed">
          This mosque has served the local community for decades but now needs
          urgent renovation. Donations will help repair the structure, improve
          facilities, and create a comfortable place of worship for hundreds of
          people.
        </p>
      </div>
    </div>
  );
};

export default CampaignDetails;
