import { getAboutInfo } from "@/components/actions/server/about";
import Link from "next/link";
import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by Humanity",
};

const About = async () => {
  const aboutWsf = await getAboutInfo();
  return (
    <div className="min-h-screen">
      <div className="text-center my-6">
        <h2 className="text-secondary text-2xl md:text-4xl font-bold">
          Making Giving Simple, Transparent, and Impactful
        </h2>
        <p className="text-accent-content md:font-bold my-3">
          WSF is a platform dedicated to connecting generous hearts with
          meaningful causes. From supporting education to funding community
          campaigns, <br />
          we make it easy for you to contribute and see the impact of your
          support
        </p>
      </div>
      <div className="grid grid-cols-1 gap-4">
        {aboutWsf.map((story) => (
          <div
            key={story.id}
            className="card bg-base-100 shadow-lg border border-base-300  rounded-lg hover:shadow-xl hover:border-primary transition-shadow duration-300"
          >
            <div className="card-body">
              <h3 className="card-title text-lg md:text-xl font-bold text-secondary">
                {story.title}
              </h3>
              <p className="text-gray-700 mt-2">{story.description}</p>
            </div>
          </div>
        ))}
      </div>
      <div className="my-6 flex flex-col md:flex-row justify-center items-center gap-4">
        <Link href={"/login"} className="btn btn-xs md:btn-md btn-primary ">
          Be a Member
        </Link>
        <Link href={"/campaigns"} className="btn btn-xs md:btn-md btn-primary ">
          Browse Campaings
        </Link>
      </div>
    </div>
  );
};

export default About;
