import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: {
    default: "WSF-Wazkruni Somajkallan Foundation",
    template: "%s | WSF-Wazkruni Somajkallan Foundation",
  },
  description: "Generated by Humanity",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased`}>
          <header className="w-11/12 mx-auto ">
            <Navbar />
          </header>
          <main className="w-11/12 mx-auto">{children}</main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
